# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recruitment_development
test:
  <<: *default
  database: recruitment_test
production:
  <<: *default
